version: "3.9"
services:
    frontend_ngrok:
        container_name: frontend_ngrok
        image: bot_app
        build: frontend/
            # context: frontend
            # dockerfile: frontend/Dockerfile
        restart: always
        ports:
            - "9000:9000"
    node_server_bot_app:
        container_name: node_server_bot_app
        build: backend/
        image: node_live_app
        ports:
            - "3000:3000"
        env_file:
            - backend/.env
        depends_on:
            - bot_node_db
        restart: always
    bot_node_db:
        container_name: bot_node_db
        image: postgres:14
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_DB=reminder
        - POSTGRES_PASSWORD=12345
        - POSTGRES_USER=postgres
        volumes:
        - node_db_data:/var/lib/postgresql/data
    ngrok_front:
        image: wernight/ngrok
        volumes:
        - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
        ports:
        - "4040:4040"
        command: ["ngrok", "http", "frontend_ngrok:9000"]
    
    #unlike try to connect to database from node js using ngrok

    # ngrok_server:
    #     image: wernight/ngrok
    #     volumes:
    #     - ./ngrok.server.yml:/home/ngrok/.ngrok2/ngrok.yml
    #     ports:
    #     - "4040:4040"
    #     command: ["ngrok", "http", "node_server_bot_app:3000"]
    # ngrok_db:
    #     image: wernight/ngrok
    #     volumes:
    #     - ./ngrok.db.yml:/home/ngrok/.ngrok2/ngrok.yml
    #     ports:
    #     - "5040:4040"
    #     command: ["ngrok", "http", "bot_node_db:5432"]

volumes:
  node_db_data: {}